### PR TITLE
Add styles so that GridFieldOrderableRows works

### PR DESCRIPTION
**Pull request by MattyBalaam**
I had the same issue as https://github.com/colymba/GridFieldGalleryTheme/issues/11

I have added some styles which work for me, but note I do not know if this will conflict with SortableGridField.

### CODE REVIEW

**Comment by colymba** [comment]
Could you post a quick screenshot?

**Comment by MattyBalaam** [comment]
Sure, I am away from my dev machine today, but will get this done this week.

**Comment by MattyBalaam** [comment]
draggable image gallery

**Comment by colymba** [comment]
Thanks. I think it look good with the drag handle like that.

I looked into it and I think it will conflict with SortableGridField since both use extensions use the `ui-sortable` class. I think we are better off making a separate CSS block (outside the main style) for this and add in the `ss-gridfield-orderable` class (which is added on the fieldset) to make sure this only affects people using GridFieldOrderableRows.

then we can just squash and merge :)

**Pull request closed without merging**
